services:
  web:
    build: .
    container_name: alt_web01
    ports:
      - "15002:8000"
    environment:
      - SECRET_KEY=change-me-in-production
    restart: always
    networks:
      - app-network

networks:
  app-network:
